import { ExtensionWrapper } from "@kn/common";
import {
	HeadingExtension, BlockquoteExtension, BoldExtension,
	UnderlineExtension, StrikeExtension, TableExtension, OrderListExtension,
	HorizontalRuleExtension, ItalicExtension, TypographyExtension,
	DropcursorExtension, GapcursorExtension, CodeExtension, CodeblockExtension, DragableExtension, TextAlignExtension, InfoPanelExtension,
	SubscriptExtension, SuperScriptExtension, ColumnsExtension, ColorExtension, HardBreakExtension, TitleExtension, LinkExtension,
	BulletListExtension, DateExtension, EmojiExtension, KnowledgeMathExtension, BackGroundColorExtension, FigmaExtension, LoadingExtension,
	TaskListExtension, PageContentExtension, MarkDownExtension, IdentExtension, LineHeightExtension, CommentExtension, FormatPainterExtension, TableOfContentExtension, EventExtension, SelectionExtension, UnknownNodeExtension, HighlightExtension, DetailsExtension
} from "../extensions";

export const buildInExtension: ExtensionWrapper[] = [
	HeadingExtension,
	UnderlineExtension,
	ItalicExtension,
	TableExtension,
	DragableExtension,
	LinkExtension,
	ColumnsExtension,
	HorizontalRuleExtension,
	StrikeExtension,
	BoldExtension,
	OrderListExtension,
	BulletListExtension,
	InfoPanelExtension,
	CodeblockExtension,
	ColorExtension,
	TextAlignExtension,
	EmojiExtension,
	DateExtension,
	BackGroundColorExtension,
	TypographyExtension,
	BlockquoteExtension,
	SuperScriptExtension,
	SubscriptExtension,
	CodeExtension,
	HardBreakExtension,
	GapcursorExtension,
	DropcursorExtension,
	MarkDownExtension,
	TitleExtension,
	KnowledgeMathExtension,
	FigmaExtension,
	LoadingExtension,
	TaskListExtension,
	PageContentExtension,
	IdentExtension,
	LineHeightExtension,
	CommentExtension,
	FormatPainterExtension,
	EventExtension,
	SelectionExtension,
	UnknownNodeExtension,
	HighlightExtension,
	DetailsExtension
]