import { ExtensionWrapper } from "@repo/common";
import {
	HeadingExtension, BlockquoteExtension, BoldExtension,
	UnderlineExtension, StrikeExtension, TableExtension, OrderListExtension,
	HorizontalRuleExtension, ItalicExtension, TypographyExtension,
	DropcursorExtension, GapcursorExtension, CodeExtension, CodeblockExtension, DragableExtension, TextAlignExtension, InfoPanelExtension,
	SubscriptExtension, SuperScriptExtension, ColumnsExtension, ColorExtension, HardBreakExtension, TitleExtension, LinkExtension, ImageExtension,
	BulletListExtension, DateExtension, EmojiExtension, DatabaseExtension, KnowledgeMathExtension, BackGroundColorExtension, FigmaExtension, LoadingExtension, ExcalidrawExtension,
	TaskListExtension, AIExtension, NoteMarkExtension, PageContentExtension, FlowExtension, MarkDownExtension, SyncBlockExtension, MindMapExtension, IdentExtension, LineHeightExtension
} from "../extensions";

export const buildInExtension: ExtensionWrapper[] = [
	AIExtension,
	HeadingExtension,
	UnderlineExtension,
	ItalicExtension,
	TableExtension,
	DragableExtension,
	// StatusExtension,
	LinkExtension,
	ColumnsExtension,
	HorizontalRuleExtension,
	StrikeExtension,
	BoldExtension,
	ImageExtension,
	// MindExtension,
	OrderListExtension,
	BulletListExtension,
	FlowExtension,
	InfoPanelExtension,
	// CommentExtension,
	CodeblockExtension,
	ColorExtension,
	// SheetExtension,
	TextAlignExtension,
	EmojiExtension,
	DateExtension,
	// CarouselExtension,
	// IFrameExtension,
	// AiExtension,
	BackGroundColorExtension,
	TypographyExtension,
	BlockquoteExtension,
	SuperScriptExtension,
	SubscriptExtension,
	CodeExtension,
	HardBreakExtension,
	GapcursorExtension,
	DropcursorExtension,
	MarkDownExtension,
	DatabaseExtension,
	TitleExtension,
	KnowledgeMathExtension,
	FigmaExtension,
	LoadingExtension,
	ExcalidrawExtension,
	TaskListExtension,
	// NoteMarkExtension,
	PageContentExtension,
	SyncBlockExtension,
	MindMapExtension,
	IdentExtension,
	LineHeightExtension
]