
import { KPlugin, PluginConfig } from "@kn/common"
import { AIExtension } from "./ai"

interface AiPluginConfig extends PluginConfig {



}
class AiPlugin extends KPlugin<AiPluginConfig> {
}

export const ai = new AiPlugin({
    status: '',
    name: 'Mermaid',
    editorExtension: [AIExtension],
    locales: {
        en: {
            translation: {
                "ai": {
                    "title": "Generated by AI"
                }
            }
        },
        zh: {
            translation: {
                "ai": {
                    "title": "此文本由AI生成"
                }
            }
        }
    }
})