
import { KPlugin, PluginConfig } from "@kn/common"
import { AIExtension } from "./ai"

interface AiPluginConfig extends PluginConfig {
    /**
     * API endpoint for AI text generation
     */
    apiEndpoint?: string;
    /**
     * API key for AI services
     */
    apiKey?: string;
    /**
     * Image generation API endpoint
     */
    imageApiEndpoint?: string;
}

class AiPlugin extends KPlugin<AiPluginConfig> {
}

export const ai = new AiPlugin({
    status: '',
    name: 'AI Assistant',
    editorExtension: [AIExtension],
    locales: {
        en: {
            translation: {
                "ai": {
                    "title": "Generated by AI",
                    "generate": "AI generating",
                    "generating": "Generating...",
                    "generateDate": "Generated on",
                    "promptLabel": "Prompt",
                    "promptPlaceholder": "Enter AI generation prompt...",
                    "imagePromptPlaceholder": "Enter image description...",
                    "delete": "Delete",
                    "tools": "AI Tools",
                    "changeTone": "Change Tone",
                    "translate": "Translate",
                    "imagePreview": "Preview",
                    "generatedImage": "AI Generated Image",
                    "imageGenerationFailed": "Image generation failed",
                    "imageGenerationError": "Image generation error"
                }
            }
        },
        zh: {
            translation: {
                "ai": {
                    "title": "此文本由AI生成",
                    "generate": "AI生成中",
                    "generating": "生成中...",
                    "generateDate": "生成日期",
                    "promptLabel": "提示语",
                    "promptPlaceholder": "请输入AI生成的提示语...",
                    "imagePromptPlaceholder": "请输入图片生成的描述...",
                    "delete": "删除",
                    "tools": "AI 工具",
                    "changeTone": "改变语气",
                    "translate": "翻译",
                    "imagePreview": "预览",
                    "generatedImage": "AI生成的图片",
                    "imageGenerationFailed": "图片生成失败",
                    "imageGenerationError": "图片生成错误"
                }
            }
        }
    }
})