
import { KPlugin, PluginConfig } from "@kn/common"
import { AIExtension } from "./ai"
import { AISettings } from "./ai/AISettings"
import { chatDockPanel } from "./dock/ChatDockPanel"
import { Sparkles } from "@kn/icon"
import React from "react"

interface AiPluginConfig extends PluginConfig {
    /**
     * API endpoint for AI text generation
     */
    apiEndpoint?: string;
    /**
     * API key for AI services
     */
    apiKey?: string;
    /**
     * Image generation API endpoint
     */
    imageApiEndpoint?: string;
}

class AiPlugin extends KPlugin<AiPluginConfig> {
}

export const ai = new AiPlugin({
    status: '',
    name: 'AI Assistant',
    editorExtension: [AIExtension],
    dockPanels: [chatDockPanel],
    settings: {
        key: 'ai-settings',
        label: 'AI 助手',
        description: '配置 AI 文本生成、图像生成和智能功能',
        icon: React.createElement(Sparkles, { className: "h-4 w-4" }),
        component: AISettings
    },
    // 插件自定义引导:无需改核心,通过 START_TOUR 事件触发(id: 'ai-intro')
    tours: [
        {
            id: 'ai-intro',
            name: 'AI 助手上手',
            trigger: 'manual',
            steps: [
                {
                    id: 'open',
                    target: '[data-tour="/ai-assistant"]',
                    title: '试试 AI 助手',
                    description: '点这里随时唤起 AI,或在文档里输入 /ai 直接调用。',
                    placement: 'right',
                    allowInteraction: true,
                },
            ],
        },
    ],
    locales: {
        en: {
            translation: {
                "dock": {
                    "agentNoEditor": "Open a page to chat with the agent"
                },
                "ai": {
                    "title": "Generated by AI",
                    "generate": "AI generating",
                    "generating": "Generating...",
                    "generateDate": "Generated on",
                    "promptLabel": "Prompt",
                    "promptPlaceholder": "Enter AI generation prompt...",
                    "imagePromptPlaceholder": "Enter image description...",
                    "delete": "Delete",
                    "tools": "AI Tools",
                    "changeTone": "Change Tone",
                    "translate": "Translate",
                    "imagePreview": "Preview",
                    "generatedImage": "AI Generated Image",
                    "imageGenerationFailed": "Image generation failed",
                    "imageGenerationError": "Image generation error",
                    "chat": {
                        "trackingHint": "Track document changes; review and merge them in the editor",
                        "trackingOn": "Tracking",
                        "trackingOff": "Track changes"
                    }
                }
            }
        },
        zh: {
            translation: {
                "dock": {
                    "agentNoEditor": "打开一篇文档后再与智能体对话"
                },
                "ai": {
                    "title": "此文本由AI生成",
                    "generate": "AI生成中",
                    "generating": "生成中...",
                    "generateDate": "生成日期",
                    "promptLabel": "提示语",
                    "promptPlaceholder": "请输入AI生成的提示语...",
                    "imagePromptPlaceholder": "请输入图片生成的描述...",
                    "delete": "删除",
                    "tools": "AI 工具",
                    "changeTone": "改变语气",
                    "translate": "翻译",
                    "imagePreview": "预览",
                    "generatedImage": "AI生成的图片",
                    "imageGenerationFailed": "图片生成失败",
                    "imageGenerationError": "图片生成错误",
                    "chat": {
                        "trackingHint": "跟踪文档变动，可在编辑器中审阅并合并",
                        "trackingOn": "跟踪中",
                        "trackingOff": "跟踪变动"
                    }
                }
            }
        }
    }
})