<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.knowledge</groupId>
        <artifactId>Knowledge</artifactId>
        <version>3.4.1</version>
    </parent>

    <artifactId>knowledge-service</artifactId>
    <name>${project.artifactId}</name>
    <version>3.4.1</version>
    <packaging>pom</packaging>
    <description>Springknowledge 微服务集合</description>

    <modules>
        <module>knowledge-log</module>
        <module>knowledge-system</module>
        <module>knowledge-wiki</module>
        <module>knowledge-message</module>
        <module>knowledge-file-center</module>
        <module>knowledge-agent-skills</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.knowledge</groupId>
            <artifactId>knowledge-common</artifactId>
            <version>${knowledge.project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>
    </dependencies>
</project>
