server:
  port: 7780

spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  data:
    redis:
      host: ${blade.redis.dev.host:127.0.0.1}
      port: ${blade.redis.dev.port:6379}
      password: ${blade.redis.dev.password:}
      database: 0

