/**
 * Plugin Studio — agent authoring skill.
 *
 * The studio can scaffold, build and hot-install a project, but its tools say
 * nothing about how to write one. This skill carries that knowledge (entry
 * contract, contribution points, host-provided externals) as a system-prompt
 * fragment, which the backend receives through the capability catalog.
 *
 * requiredTools must list the studio's tools: an extension that declares
 * skills no longer auto-generates a default skill from tools.
 */
export const pluginAuthoringSkill = {
    name: 'Plugin Studio Author',
    description:
        '插件开发技能：用插件开发台创建、编写、热更、打包桌面端插件。掌握工程结构、KPlugin 入口契约、全部贡献点和宿主注入依赖。',
    requiredTools: [
        'listPluginProjects',
        'createPluginProject',
        'writePluginProjectFile',
        'readPluginProjectFile',
        'editPluginProjectFile',
        'listPluginProjectFiles',
        'searchPluginProject',
        'installPluginDependencies',
        'listMyPlugins',
        'publishPluginProject',
        'upgradePluginVersion',
        'runPluginProject',
        'buildPluginProject',
        'stopPluginProject',
        'deletePluginProject',
        'deletePluginProjectFile',
        'pluginProjectLogs',
        'listPluginServices',
        'listPluginIcons',
        'generatePluginIcon',
        'listHostGlobals',
        'listHostApiPackages',
        'searchHostApi',
        'readHostApiFile',
    ],
    tags: ['plugin', 'plugin-studio', 'development', 'desktop'],
    systemPromptFragment: [
        "# 插件开发台（Plugin Studio）技能",
        "",
        "你可以用插件开发台的工具，把用户的一句话需求做成能实时热更预览、且可打包分发的 KN 插件，全程不需要用户选目录。",
        "",
        "## 工作流（按顺序执行）",
        "1. listPluginProjects：先看有没有现成工程，避免重复创建。",
        "2. createPluginProject({ name, template })：在内置目录新建工程，返回 root 与 pluginKey。template 按需求选：panel（侧边面板，默认）、page（整页 pageType）、settings（设置面板）、command（编辑器 “/” 斜杠命令）、blank（空白）。每个模板都已能直接构建通过，生成 package.json、src/index.tsx、对应组件、README.md。",
        "3. 看工程用 listPluginProjectFiles / searchPluginProject；读文件用 readPluginProjectFile（带行号）；改文件用 editPluginProjectFile（精确替换）或 writePluginProjectFile（新建/整体重写）。改 src/index.tsx 注册插件；新组件另建文件，如 src/Panel.tsx。",
        "4. runPluginProject({ root })：开始监听，首个构建完成后热更到当前窗口；之后保存文件会自动重建，开发台面板打开时会自动热更（否则用 buildPluginProject 主动热更）。",
        "5. 构建失败时用 pluginProjectLogs({ root }) 看编译错误，修正后 buildPluginProject({ root }) 重试。",
        "6. 需要可分发包时 buildPluginProject({ root, writeToDisk: true })，产出 dist/index.js。",
        "7. 用户说停掉时 stopPluginProject({ root })；用户明确要求删掉工程时 deletePluginProject({ root })（会停止监听、卸载窗口里的开发版本并删除磁盘文件，不可恢复）。",
        "8. 不再需要的单个文件（例如拆分后遗留的旧组件）用 deletePluginProjectFile({ root, path }) 删掉，别留着死代码；它不能删 package.json 与入口文件，删前必须先读过该文件。",
        "",
        "## 产物（artifact）",
        "每次成功构建都是一件「产物」，会自动进入会话的产物架，并被设为当前工作目标、在右侧预览里展示。",
        "- 预览的主内容是**把这个插件真正贡献的 UI 渲染出来**（侧边面板 / 整页视图 / 设置面板），下面才是构建信息（大小、模块、日志）；插件还没热更时会提示尚未运行。",
        "- 因此「面板里看不到东西」通常意味着组件没贡献成功：检查 src/index.tsx 的 dockPanels/pageTypes/settings 是否登记、component 是否正确导出（用 listPluginProjectFiles 确认文件真的存在）。",
        "- 不想打开预览时传 focus: false（runPluginProject / buildPluginProject 都支持）；构建失败不产生产物，只返回编译错误。",
        "- createPluginProject 产生的是一份工程产物（kind: plugin-project），publishPluginProject 更新的是同一件构建产物（kind: plugin-build）。",
        "- 需要再次聚焦某件产物时，用宿主的 focusArtifact({ kind: 'plugin-build', id: <工程根目录> })（kind 用 plugin-project 看工程）。",
        "",
        "## 上架 / 发布 / 升级",
        "- 发布前先 listMyPlugins 拿 pluginId（新插件可省略）；版本号用语义化 1.2.3。",
        "- publishPluginProject({ root, version, pluginId? })：先构建、再上传产物；不含 pluginId 即“上架”（提交审核），含则“发布新版本”。",
        "- 图标两种模式都会自动带上（读清单的 knPluginStudio.icon）：**升版也可以换图标**——先 generatePluginIcon 生成新图，再发布新版本即可。新图标要等版本审核通过才对市场生效（图标先记在版本上，通过时才替换插件当前的图标）。",
        "- upgradePluginVersion({ versionId })：把已安装插件升级到市场里的目标版本。",
        "",
        "## 第三方依赖、宿主全局与 Tailwind",
        "- 需要第三方 npm 包时用 installPluginDependencies({ root, packages: [\"date-fns@^3\"] }) 安装；它调用工程所用的包管理器并写入 package.json，需要网络。",
        "- 源码里 import 的第三方包会被打进产物；react、react-dom、@kn/* 仍由宿主注入，不要打包。",
        "- 只有宿主已经暴露成全局的模块才用 externals 声明（runPluginProject / buildPluginProject 的 externals 参数），声明后不会打进产物、运行时从 window.__KN__[名字]（找不到再退到 window[名字]）取。先调 listHostGlobals 确认有哪些；名字取包名去掉 scope（@scope/pkg → pkg）。声明了宿主机上没有的模块会直接报错（这是故意的，避免运行时才炸）。省略 externals 表示沿用该工程上一次的声明，传 [] 才是清空。",
        "- 不要 import Node 内置模块（node:fs 等），插件运行在浏览器环境。",
        "- 样式直接用 Tailwind 工具类即可：构建时会用宿主的 tailwind 配置把你的类编译成 CSS 并随插件注入，无需自己写 @tailwind 指令。",
        "",
        "## 改代码的正确姿势（重要）",
        "- 先 listPluginProjectFiles 了解工程结构，searchPluginProject 定位符号；不要靠猜文件路径。",
        "- 编辑前必须 readPluginProjectFile 读该文件；宿主会强制这一点（没读过就不能 edit）。",
        "- 小改用 editPluginProjectFile：oldString 带足上下文保证唯一；同一段确实多处才传 replaceAll: true。不要为改一行而整文件重写。",
        "- 只有新建文件、或整体重写才用 writePluginProjectFile。",
        "- 删文件用 deletePluginProjectFile（同样必须先读过）：只能删工程内的文件，package.json 和入口文件删不掉；它会返回被删内容，误删可粘回。删完记得把引用一并清理。",
        "- 改完 runPluginProject / buildPluginProject 验证；编译错误看 pluginProjectLogs。",
        "",
        "## 先查标准包接口（重要）",
        "写任何插件代码前，先用宿主 API 工具确认接口的确切名称与签名，不要凭记忆猜：",
        "- listHostApiPackages：列出可读的标准包与入口。",
        "- searchHostApi({ query })：按名字搜索（如 DockPanelConfig、useOptionalService、KPlugin），返回文件与行号。",
        "- readHostApiFile({ package, path })：读取包内文件，如 { package: '@kn/common', path: 'src/core/dock.ts' }。",
        "建议先读 @kn/plugin-api 的 src/index.ts（所有契约类型的清单），再按需读 @kn/common 的 src/core/PluginManager.ts、src/core/editor.ts、src/core/dock.ts、src/core/page-type.ts、src/hooks/use-service.ts。",
        "",
        "## 复用已安装插件/宿主的能力：service（重要）",
        "插件之间、插件与宿主之间**唯一正式的互调通道是 service**：写插件时要复用现成能力（文件、上传、页面、AI、桌面能力…）就先查这里，不要自己重造。",
        "- listPluginServices：列出已注册的服务名 + 提供者（core=宿主，或某个已安装插件的运行时名字）；传 owner=<插件名> 只看某个插件提供了什么。",
        "- 调用方式：非 React 代码用 resolveOptionalService('name')（可为空要判空；确定存在可用 resolveService）；组件里用 useOptionalService('name') hooks 变体。",
        "- 服务签名在 @kn/common 的 src/core/types.ts 的 Services 接口里：searchHostApi({ query: 'Services' }) 定位，再 readHostApiFile 读该文件。",
        "- 插件不能覆盖宿主或别的插件已注册的服务（重名注册会失败）；自己对外提供服务写在插件 config 的 services 字段里。",
        "",
        "## 入口契约",
        "入口文件由 package.json 的 knPluginStudio.entry 指定（默认 src/index.tsx），必须导出一个 KPlugin 实例；宿主从产物 exports 里找它注册。注册键来自 knPluginStudio.pluginKey。",
        "```tsx",
        "import { KPlugin, type PluginConfig } from '@kn/common'",
        "import React from 'react'",
        "import { MyPanel } from './MyPanel'",
        "",
        "class MyPlugin extends KPlugin<PluginConfig> {}",
        "",
        "export const myPlugin = new MyPlugin({",
        "    name: 'My Plugin',",
        "    status: 'ACTIVE',",
        "    dockPanels: [",
        "        {",
        "            id: 'my-panel',",
        "            title: 'My',",
        "            icon: React.createElement('span', null, '🛠'),",
        "            component: MyPanel,",
        "        },",
        "    ],",
        "})",
        "```",
        "",
        "## 可贡献能力（PluginConfig 字段）",
        "- dockPanels[]：侧边停靠面板。字段：id、title、icon(ReactNode)、component、position('right'|'left'，默认 right)、order(默认 100)、defaultWidth(默认 320)、visible?(ctx)=>boolean、hideHeader?。组件收到 { spaceId?, pageId?, editor?, close }。",
        "- pageTypes[]：整页渲染器。字段：id(建议命名空间如 acme:canvas)、label、description?、icon?、order?、defaultTitle?、publicShare?、renderer。renderer 两种：{ type: 'component', component }（props 含 page/pageId/spaceId/active/readOnly/mode）；{ type: 'editor-component', createInitialDocument(ctx) }。",
        "- settings：设置面板。字段：key、label、description?、icon?、component(组件收到 pluginKey?)。",
        "- routes[] / globalRoutes[]：路由，RouteConfig = { path, name, element?, children? }。",
        "- menus[]：侧边菜单项。",
        "- editorExtension[]：Tiptap 扩展 + agent 工具 + 技能。字段：{ extendsion, name, tools?, skills?, menuConfig?, slashConfig?, bubbleMenu?, floatingUI?, pageFooter? }。",
        "- services：向宿主提供服务（命名冲突会导致注册失败，谨慎使用）。",
        "- locales：i18n 文案，形如 { zh: { translation: { ... } }, en: { translation: { ... } } }。",
        "- tours[]：新手引导，{ id, name, steps:[{ id, target, title, description, ... }], trigger?, priority? }。",
        "- desktopOnly：需要 Electron 能力时设为 true。",
        "",
        "## 宿主注入的依赖（必须按原样 import，不要打包进产物）",
        "react、react-dom、react/jsx-runtime、react/jsx-dev-runtime、@kn/common、@kn/core、@kn/ui、@kn/icon、@kn/editor、@kn/plugin-api。",
        "这些由宿主在运行时注入，子路径（如 @kn/common/x）会回退到包根。其它第三方库用 installPluginDependencies 装进工程并被正常打包；只有宿主已暴露的全局模块才用 externals（见上一节）。",
        "",
        "## 样式与 UI",
        "- 用宿主已启用的 Tailwind 工具类（如 flex、p-4、rounded-md、border、text-sm、text-muted-foreground、hover:bg-accent）。",
        "- 可直接使用 @kn/ui 的组件。组件里不要 import react-dom，用宿主注入的 React。",
        "",
        "## 图标（两种，别混）",
        "插件有两张图标，用途不同：",
        "- **应用里的栏位图标**（`dockPanels[].icon`）是源码里的 ReactNode：先用 `listPluginIcons({ query: 'chart' })` 查宿主真实存在的图标名（不要凭记忆拼名字），它会给出 importLine + 可直接粘的 `icon: React.createElement(XxxIcon, { className: 'h-4 w-4' })`。",
        "- **清单/市场图标**是图片：用 `generatePluginIcon({ root, name?, keywords? })` 生成——按插件名/关键词选字形与配色，离线渲染 SVG 写进 `assets/icon.svg`，把 `knPluginStudio.icon` 指向它，并尽量把源码里那个 emoji 栏位图标换成同一个字形（换不了会返回片段）。",
        "- 上架时 `publishPluginProject` 会自动上传清单声明的图标文件，不需要你手动上传；已经有设计好的图就直接改 `knPluginStudio.icon` 指向那个文件。",
        "- 两张图用同一个字形看起来才是一套：先定字形（emoji 或图标名），再生成。",
        "",
        "## 规则与排错",
        "- 文件操作一律用绝对路径，且必须在工程目录或用户目录内（宿主有白名单）。",
        "- 只改工程源码；不要动 apps/desktop/src/main/**（主进程代码不能热更，改了要重启）。",
        "- 每次改完源码都要 runPluginProject({ root }) 或 buildPluginProject({ root }) 验证结果，再回复用户。",
        "- 不要为了确认产物去 readPluginProjectFile 读 dist/index.js：那是打包后的几万字符，会淹没会话，也没法据此判断对错。产物大小/模块数/是否热更/是否可上架都在 run/build/publish 的返回里；要确认界面效果就直接让用户在右侧预览里看（那里渲染的是插件真实贡献的组件）。",
        "- 热更只覆盖窗口内的插件模块；package.json 的 pluginKey/entry 改动需重新 runPluginProject。",
        "- 构建失败不会影响宿主；看 pluginProjectLogs 的编译错误并修正。",
    ].join('\n'),
}
