/**
 * Plugin Studio — agent authoring skill.
 *
 * The studio can scaffold, build and hot-install a project, but its tools say
 * nothing about how to write one. This skill carries that knowledge (entry
 * contract, contribution points, host-provided externals) as a system-prompt
 * fragment, which the backend receives through the capability catalog.
 *
 * requiredTools must list the studio's tools: an extension that declares
 * skills no longer auto-generates a default skill from tools.
 */
export const pluginAuthoringSkill = {
    name: 'Plugin Studio Author',
    description:
        '插件开发技能：用插件开发台创建、编写、热更、打包桌面端插件。掌握工程结构、KPlugin 入口契约、全部贡献点和宿主注入依赖。',
    requiredTools: [
        'listPluginProjects',
        'createPluginProject',
        'writePluginProjectFile',
        'readPluginProjectFile',
        'editPluginProjectFile',
        'listPluginProjectFiles',
        'searchPluginProject',
        'runPluginProject',
        'buildPluginProject',
        'stopPluginProject',
        'pluginProjectLogs',
        'listHostApiPackages',
        'searchHostApi',
        'readHostApiFile',
    ],
    tags: ['plugin', 'plugin-studio', 'development', 'desktop'],
    systemPromptFragment: [
        "# 插件开发台（Plugin Studio）技能",
        "",
        "你可以用插件开发台的工具，把用户的一句话需求做成能实时热更预览、且可打包分发的 KN 插件，全程不需要用户选目录。",
        "",
        "## 工作流（按顺序执行）",
        "1. listPluginProjects：先看有没有现成工程，避免重复创建。",
        "2. createPluginProject({ name })：在内置目录新建工程，返回 root 与 pluginKey。生成 package.json、src/index.tsx、src/DevPanel.tsx、README.md。",
        "3. 看工程用 listPluginProjectFiles / searchPluginProject；读文件用 readPluginProjectFile（带行号）；改文件用 editPluginProjectFile（精确替换）或 writePluginProjectFile（新建/整体重写）。改 src/index.tsx 注册插件；新组件另建文件，如 src/Panel.tsx。",
        "4. runPluginProject({ root })：开始监听，首个构建完成后热更到当前窗口；之后保存文件会自动重建热更。",
        "5. 构建失败时用 pluginProjectLogs({ root }) 看编译错误，修正后 buildPluginProject({ root }) 重试。",
        "6. 需要可分发包时 buildPluginProject({ root, writeToDisk: true })，产出 dist/index.js。",
        "7. 用户说停掉时 stopPluginProject({ root })。",
        "",
        "## 改代码的正确姿势（重要）",
        "- 先 listPluginProjectFiles 了解工程结构，searchPluginProject 定位符号；不要靠猜文件路径。",
        "- 编辑前必须 readPluginProjectFile 读该文件；宿主会强制这一点（没读过就不能 edit）。",
        "- 小改用 editPluginProjectFile：oldString 带足上下文保证唯一；同一段确实多处才传 replaceAll: true。不要为改一行而整文件重写。",
        "- 只有新建文件、或整体重写才用 writePluginProjectFile。",
        "- 改完 runPluginProject / buildPluginProject 验证；编译错误看 pluginProjectLogs。",
        "",
        "## 先查标准包接口（重要）",
        "写任何插件代码前，先用宿主 API 工具确认接口的确切名称与签名，不要凭记忆猜：",
        "- listHostApiPackages：列出可读的标准包与入口。",
        "- searchHostApi({ query })：按名字搜索（如 DockPanelConfig、useOptionalService、KPlugin），返回文件与行号。",
        "- readHostApiFile({ package, path })：读取包内文件，如 { package: '@kn/common', path: 'src/core/dock.ts' }。",
        "建议先读 @kn/plugin-api 的 src/index.ts（所有契约类型的清单），再按需读 @kn/common 的 src/core/PluginManager.ts、src/core/editor.ts、src/core/dock.ts、src/core/page-type.ts、src/hooks/use-service.ts。",
        "",
        "## 入口契约",
        "入口文件由 package.json 的 knPluginStudio.entry 指定（默认 src/index.tsx），必须导出一个 KPlugin 实例；宿主从产物 exports 里找它注册。注册键来自 knPluginStudio.pluginKey。",
        "```tsx",
        "import { KPlugin, type PluginConfig } from '@kn/common'",
        "import React from 'react'",
        "import { MyPanel } from './MyPanel'",
        "",
        "class MyPlugin extends KPlugin<PluginConfig> {}",
        "",
        "export const myPlugin = new MyPlugin({",
        "    name: 'My Plugin',",
        "    status: 'ACTIVE',",
        "    dockPanels: [",
        "        {",
        "            id: 'my-panel',",
        "            title: 'My',",
        "            icon: React.createElement('span', null, '🛠'),",
        "            component: MyPanel,",
        "        },",
        "    ],",
        "})",
        "```",
        "",
        "## 可贡献能力（PluginConfig 字段）",
        "- dockPanels[]：侧边停靠面板。字段：id、title、icon(ReactNode)、component、position('right'|'left'，默认 right)、order(默认 100)、defaultWidth(默认 320)、visible?(ctx)=>boolean、hideHeader?。组件收到 { spaceId?, pageId?, editor?, close }。",
        "- pageTypes[]：整页渲染器。字段：id(建议命名空间如 acme:canvas)、label、description?、icon?、order?、defaultTitle?、publicShare?、renderer。renderer 两种：{ type: 'component', component }（props 含 page/pageId/spaceId/active/readOnly/mode）；{ type: 'editor-component', createInitialDocument(ctx) }。",
        "- settings：设置面板。字段：key、label、description?、icon?、component(组件收到 pluginKey?)。",
        "- routes[] / globalRoutes[]：路由，RouteConfig = { path, name, element?, children? }。",
        "- menus[]：侧边菜单项。",
        "- editorExtension[]：Tiptap 扩展 + agent 工具 + 技能。字段：{ extendsion, name, tools?, skills?, menuConfig?, slashConfig?, bubbleMenu?, floatingUI?, pageFooter? }。",
        "- services：向宿主提供服务（命名冲突会导致注册失败，谨慎使用）。",
        "- locales：i18n 文案，形如 { zh: { translation: { ... } }, en: { translation: { ... } } }。",
        "- tours[]：新手引导，{ id, name, steps:[{ id, target, title, description, ... }], trigger?, priority? }。",
        "- desktopOnly：需要 Electron 能力时设为 true。",
        "",
        "## 宿主注入的依赖（必须按原样 import，不要打包进产物）",
        "react、react-dom、react/jsx-runtime、react/jsx-dev-runtime、@kn/common、@kn/core、@kn/ui、@kn/icon、@kn/editor、@kn/plugin-api。",
        "这些由宿主在运行时注入，子路径（如 @kn/common/x）会回退到包根。不要 import 其它第三方库；当前 agent 工具不支持传 externals，因此只用上面这些包。",
        "",
        "## 样式与 UI",
        "- 用宿主已启用的 Tailwind 工具类（如 flex、p-4、rounded-md、border、text-sm、text-muted-foreground、hover:bg-accent）。",
        "- 可直接使用 @kn/ui 的组件。组件里不要 import react-dom，用宿主注入的 React。",
        "",
        "## 规则与排错",
        "- 文件操作一律用绝对路径，且必须在工程目录或用户目录内（宿主有白名单）。",
        "- 只改工程源码；不要动 apps/desktop/src/main/**（主进程代码不能热更，改了要重启）。",
        "- 每次改完源码都要 runPluginProject({ root }) 或 buildPluginProject({ root }) 验证结果，再回复用户。",
        "- 热更只覆盖窗口内的插件模块；package.json 的 pluginKey/entry 改动需重新 runPluginProject。",
        "- 构建失败不会影响宿主；看 pluginProjectLogs 的编译错误并修正。",
    ].join('\n'),
}
