import { KPlugin, PluginConfig } from '@kn/common';
import { SpeechToTextExtension } from './extension';

interface SpeechToTextPluginConfig extends PluginConfig { }

class SpeechToTextPlugin extends KPlugin<SpeechToTextPluginConfig> { }

export const speechToText = new SpeechToTextPlugin({
    status: 'ACTIVE',
    name: 'Speech to Text',
    editorExtension: [SpeechToTextExtension],
    locales: {
        zh: {
            translation: {
                speechToText: {
                    start: '开始录音',
                    stop: '停止录音',
                    notSupported: '此浏览器不支持语音识别，请使用 Chrome 或 Edge。',
                },
                meetingMinutes: {
                    title: '会议纪要',
                    meetingTitle: '会议',
                    today: '今天',
                    notes: '笔记',
                    notesPlaceholder: '在此添加笔记，AI 会利用它们生成更智能的摘要…',
                    summary: '摘要',
                    transcript: '转录',
                    startTranscribing: '开始转录',
                    pause: '暂停',
                    resume: '继续',
                    stop: '停止',
                    transcribing: '转录中',
                    paused: '已暂停',
                    listening: '聆听中…',
                    liveTranscript: '实时转录',
                    editable: '可编辑',
                    transcriptWillAppear: '转录内容将显示在这里…',
                    processing: '处理中…',
                    generateAISummary: '生成 AI 摘要',
                    generatingSummary: '正在生成摘要…',
                    insertToEditor: '插入到编辑器',
                    chars: '字符',
                    share: '分享',
                    newRecording: '新建录音',
                    saveRecording: '保存录音',
                    howItWorks: '使用方法：',
                    howItWorks1: '点击"开始转录"开始。',
                    howItWorks2: '随时在此添加笔记，AI 会利用它们生成更智能的摘要。',
                    howItWorks3: '完成后点击"停止"，AI 将生成摘要和待办事项。',
                    consentTitle: '选择如何通知他人',
                    consentDesc: '为了让他人知道您正在录音，可以播放音频消息，或您自行获取同意。为所有会议设置默认方式：',
                    consentMyself: '自行获取同意',
                    consentAudio: '自动播放音频',
                    instructions: '说明：',
                    auto: '自动',
                    consentNote: '开始即表示您确认所有被录音的人已同意。',
                    duration: '时长：',
                    helpfulQuestion: '摘要是否有帮助？',
                    meetingTitlePlaceholder: '会议标题…',
                    noSpeechContent: '（无语音内容）',
                    tips: '提示',
                    settings: '设置',
                    copiedToClipboard: '已复制到剪贴板',
                    copyFailed: '复制失败',
                    audioSaved: '录音已保存',
                    saveFailed: '保存失败',
                    insertedToDoc: '已插入到文档',
                    volume: '音量',
                    copy: '复制',
                    recordingPlayback: '录音回放',
                    aiSummary: 'AI 摘要',
                    insertToDocument: '插入到文档',
                    summaryGenerationFailed: 'AI摘要生成失败，以下为转录内容预览',
                    recordingFilePrefix: '会议录音',
                    summaryPrompt: '请为以下会议录音转录内容生成会议摘要，包括：\n1. 会议主题/标题\n2. 主要讨论内容（按要点列出）\n3. 会议结论/决议\n4. 待办事项（如有）\n\n转录内容：\n{{transcript}}\n\n请用中文回复，格式清晰易读。',
                },
            },
        },
        en: {
            translation: {
                speechToText: {
                    start: 'Speech to text',
                    stop: 'Stop recording',
                    notSupported: 'Speech recognition is not supported in this browser. Please use Chrome or Edge.',
                },
                meetingMinutes: {
                    title: 'Meeting Minutes',
                    meetingTitle: 'Meeting',
                    today: 'Today',
                    notes: 'Notes',
                    notesPlaceholder: 'Add notes here — AI uses them to generate smarter summaries…',
                    summary: 'Summary',
                    transcript: 'Transcript',
                    startTranscribing: 'Start transcribing',
                    pause: 'Pause',
                    resume: 'Resume',
                    stop: 'Stop',
                    transcribing: 'Transcribing',
                    paused: 'Paused',
                    listening: 'Listening…',
                    liveTranscript: 'Live transcript',
                    editable: 'Editable',
                    transcriptWillAppear: 'Transcript will appear here…',
                    processing: 'Processing…',
                    generateAISummary: 'Generate AI summary',
                    generatingSummary: 'Generating summary…',
                    insertToEditor: 'Insert to editor',
                    chars: 'chars',
                    share: 'Share',
                    newRecording: 'New recording',
                    saveRecording: 'Save recording',
                    howItWorks: 'How it works:',
                    howItWorks1: 'Click "Start transcribing" to get started.',
                    howItWorks2: 'Add notes here anytime. AI uses them to make the summary smarter.',
                    howItWorks3: 'When you\'re done, click "Stop". AI will generate a summary with action items.',
                    consentTitle: 'Choose how you notify others',
                    consentDesc: 'To let others know you\'re transcribing, an audio message can play automatically, or you can continue to get consent yourself. Set your default for all meetings:',
                    consentMyself: 'Get consent myself',
                    consentAudio: 'Automatically play audio',
                    instructions: 'Instructions:',
                    auto: 'Auto',
                    consentNote: 'By starting, you confirm everyone being transcribed has given consent.',
                    duration: 'Duration:',
                    helpfulQuestion: 'Was this summary helpful?',
                    meetingTitlePlaceholder: 'Meeting title…',
                    noSpeechContent: '(No speech content)',
                    tips: 'Tips',
                    settings: 'Settings',
                    copiedToClipboard: 'Copied to clipboard',
                    copyFailed: 'Copy failed',
                    audioSaved: 'Audio saved',
                    saveFailed: 'Save failed',
                    insertedToDoc: 'Inserted to document',
                    volume: 'Volume',
                    copy: 'Copy',
                    recordingPlayback: 'Recording playback',
                    aiSummary: 'AI Summary',
                    insertToDocument: 'Insert to document',
                    summaryGenerationFailed: 'AI summary generation failed, showing transcript preview',
                    recordingFilePrefix: 'Recording',
                    summaryPrompt: 'Please generate a meeting summary for the following transcript, including:\n1. Meeting topic/title\n2. Key discussion points (listed by item)\n3. Conclusions/decisions\n4. Action items (if any)\n\nTranscript:\n{{transcript}}\n\nPlease reply in Markdown format, clear and readable.',
                },
            },
        },
    },
});

export { SpeechToTextExtension } from './extension';
export { useSpeechRecognition } from './hooks/useSpeechRecognition';
