import { KPlugin, PluginConfig } from '@kn/common';
import { SpeechToTextExtension } from './extension';
import { meetingMinutesPageType } from './meeting-page-type';

interface SpeechToTextPluginConfig extends PluginConfig { }

class SpeechToTextPlugin extends KPlugin<SpeechToTextPluginConfig> { }

export const speechToText = new SpeechToTextPlugin({
    status: 'ACTIVE',
    name: 'Speech to Text',
    editorExtension: [SpeechToTextExtension],
    pageTypes: [meetingMinutesPageType],
    locales: {
        zh: {
            translation: {
                speechToText: {
                    title: '语音转文字',
                    start: '语音输入',
                    stop: '停止',
                    pause: '暂停',
                    resume: '继续',
                    listening: '正在聆听…',
                    paused: '已暂停',
                    notSupported: '此浏览器不支持语音识别，请使用 Chrome 或 Edge。',
                },
                meetingMinutes: {
                    title: '会议纪要',
                    pageType: '会议纪要',
                    pageTypeDescription: '新建一个正文仅包含会议纪要组件的页面',
                    untitledMeeting: '未命名会议',
                    newMeeting: '插入会议纪要',
                    meetingTitle: '会议',
                    today: '今天',
                    notes: '笔记',
                    meetingSections: '会议内容',
                    notesPlaceholder: '在此记录会议笔记，AI 会结合笔记和转录生成摘要…',
                    attendees: '参会人',
                    addAttendee: '添加',
                    removeAttendee: '移除',
                    searchAttendeePlaceholder: '搜索成员…',
                    noAttendeesFound: '未找到成员',
                    tags: '标签',
                    language: '识别语言',
                    model: '摘要模型',
                    defaultModel: '默认模型',
                    loadingModels: '加载模型中…',
                    noModels: '暂无可用模型',
                    transcriptionUnavailable: '当前浏览器不支持实时转录，仍会录音（推荐使用 Chrome 或 Edge）。',
                    actionItems: '待办事项',
                    summary: '摘要',
                    transcript: '转录',
                    startTranscribing: '开始转录',
                    pause: '暂停',
                    resume: '继续',
                    stop: '停止',
                    transcribing: '转录中',
                    paused: '已暂停',
                    listening: '聆听中…',
                    liveTranscript: '实时转录',
                    editable: '可编辑',
                    transcriptWillAppear: '会议转录内容将显示在这里…',
                    processing: '处理中…',
                    requestingPermission: '正在请求麦克风权限…',
                    finalizingRecording: '正在结束录音…',
                    savingRecording: '正在保存录音…',
                    savingAndSummarizing: '正在保存录音并生成摘要…',
                    recordingFailed: '录音处理失败',
                    meetingReady: '会议记录已就绪',
                    readyToRecord: '准备开始会议记录',
                    generateAISummary: '生成 AI 摘要',
                    generatingSummary: '正在生成摘要…',
                    insertToEditor: '插入到编辑器',
                    chars: '字符',
                    share: '分享',
                    moreActions: '更多操作',
                    deleteMeeting: '删除会议纪要组件',
                    confirmDeleteMeeting: '删除此会议纪要组件会移除其中的笔记、摘要、转录和录音引用（不会删除文件中心中的录音文件）。是否继续？',
                    delete: '删除',
                    continue: '继续',
                    cancel: '取消',
                    newRecording: '新建录音',
                    confirmNewRecording: '新建录音会清空当前会议的笔记、摘要、转录和录音引用，是否继续？',
                    saveRecording: '保存录音',
                    howItWorks: '使用方法：',
                    howItWorks1: '点击"开始转录"开始。',
                    howItWorks2: '随时在此添加笔记，AI 会利用它们生成更智能的摘要。',
                    howItWorks3: '完成后点击"停止"，AI 将生成摘要和待办事项。',
                    consentTitle: '选择如何通知他人',
                    consentDesc: '为了让他人知道您正在录音，可以播放音频消息，或您自行获取同意。为所有会议设置默认方式：',
                    consentMyself: '自行获取同意',
                    consentAudio: '自动播放音频',
                    instructions: '说明：',
                    auto: '自动',
                    consentNote: '开始即表示您确认所有被录音的人已同意。',
                    duration: '时长：',
                    helpfulQuestion: '摘要是否有帮助？',
                    meetingTitlePlaceholder: '会议标题…',
                    noSpeechContent: '（无语音内容）',
                    tips: '提示',
                    settings: '设置',
                    copiedToClipboard: '已复制到剪贴板',
                    copyFailed: '复制失败',
                    audioSaved: '录音已保存',
                    saveFailed: '保存失败',
                    uploadRecordingFailed: '录音上传失败',
                    insertedToDoc: '已插入到文档',
                    volume: '音量',
                    copy: '复制',
                    recordingPlayback: '录音回放',
                    playRecording: '播放录音',
                    pausePlayback: '暂停播放',
                    playbackPosition: '录音播放进度',
                    audioPlaybackFailed: '录音播放失败，请检查录音文件是否可访问。',
                    aiSummary: 'AI 摘要',
                    insertToDocument: '插入到文档',
                    summaryGenerationFailed: 'AI 摘要生成失败',
                    summaryPlaceholder: '会议结束后会自动生成摘要、决策和待办事项…',
                    keyPoints: '讨论要点',
                    decisions: '会议决策',
                    owner: '负责人',
                    dueDate: '截止日期',
                    selectRecordingFolder: '选择会议录音文件夹',
                    fileServiceUnavailable: '文件服务不可用，录音仅保存在当前浏览器中',
                    folderNotSelected: '未选择录音文件夹，可下载本地副本或稍后重试',
                    stopFailed: '停止录音失败',
                    retrySummary: '重试摘要',
                    retrySave: '重试保存',
                    downloadLocalCopy: '下载本地副本',
                    recordingFilePrefix: '会议录音',
                    summaryPrompt: '请为以下会议录音转录内容生成会议摘要，包括：\n1. 会议主题/标题\n2. 主要讨论内容（按要点列出）\n3. 会议结论/决议\n4. 待办事项（如有）\n\n转录内容：\n{{transcript}}\n\n请用中文回复，格式清晰易读。',
                },
            },
        },
        en: {
            translation: {
                speechToText: {
                    title: 'Speech to text',
                    start: 'Speech to text',
                    stop: 'Stop',
                    pause: 'Pause',
                    resume: 'Resume',
                    listening: 'Listening…',
                    paused: 'Paused',
                    notSupported: 'Speech recognition is not supported in this browser. Please use Chrome or Edge.',
                },
                meetingMinutes: {
                    title: 'Meeting Minutes',
                    pageType: 'Meeting Minutes',
                    pageTypeDescription: 'Create a page whose body contains only the meeting-minutes component',
                    untitledMeeting: 'Untitled meeting',
                    newMeeting: 'Insert meeting minutes',
                    meetingTitle: 'Meeting',
                    today: 'Today',
                    notes: 'Notes',
                    meetingSections: 'Meeting content',
                    notesPlaceholder: 'Take meeting notes here. AI will use the notes and transcript to generate a summary…',
                    attendees: 'Attendees',
                    addAttendee: 'Add',
                    removeAttendee: 'Remove',
                    searchAttendeePlaceholder: 'Search members…',
                    noAttendeesFound: 'No members found',
                    tags: 'Tags',
                    language: 'Language',
                    model: 'Summary model',
                    defaultModel: 'Default model',
                    loadingModels: 'Loading models…',
                    noModels: 'No models available',
                    transcriptionUnavailable: 'Live transcription is unavailable in this browser; audio is still recorded (use Chrome or Edge).',
                    actionItems: 'Action items',
                    summary: 'Summary',
                    transcript: 'Transcript',
                    startTranscribing: 'Start transcribing',
                    pause: 'Pause',
                    resume: 'Resume',
                    stop: 'Stop',
                    transcribing: 'Transcribing',
                    paused: 'Paused',
                    listening: 'Listening…',
                    liveTranscript: 'Live transcript',
                    editable: 'Editable',
                    transcriptWillAppear: 'The meeting transcript will appear here…',
                    processing: 'Processing…',
                    requestingPermission: 'Requesting microphone access…',
                    finalizingRecording: 'Finalizing recording…',
                    savingRecording: 'Saving recording…',
                    savingAndSummarizing: 'Saving recording and generating summary…',
                    recordingFailed: 'Recording processing failed',
                    meetingReady: 'Meeting record is ready',
                    readyToRecord: 'Ready to start meeting notes',
                    generateAISummary: 'Generate AI summary',
                    generatingSummary: 'Generating summary…',
                    insertToEditor: 'Insert to editor',
                    chars: 'chars',
                    share: 'Share',
                    moreActions: 'More actions',
                    deleteMeeting: 'Delete meeting-minutes component',
                    confirmDeleteMeeting: 'Deleting this meeting-minutes component removes its notes, summary, transcript, and recording reference. Uploaded audio remains in File Center. Continue?',
                    delete: 'Delete',
                    continue: 'Continue',
                    cancel: 'Cancel',
                    newRecording: 'New recording',
                    confirmNewRecording: 'Starting a new recording clears the current notes, summary, transcript, and recording reference. Continue?',
                    saveRecording: 'Save recording',
                    howItWorks: 'How it works:',
                    howItWorks1: 'Click "Start transcribing" to get started.',
                    howItWorks2: 'Add notes here anytime. AI uses them to make the summary smarter.',
                    howItWorks3: 'When you\'re done, click "Stop". AI will generate a summary with action items.',
                    consentTitle: 'Choose how you notify others',
                    consentDesc: 'To let others know you\'re transcribing, an audio message can play automatically, or you can continue to get consent yourself. Set your default for all meetings:',
                    consentMyself: 'Get consent myself',
                    consentAudio: 'Automatically play audio',
                    instructions: 'Instructions:',
                    auto: 'Auto',
                    consentNote: 'By starting, you confirm everyone being transcribed has given consent.',
                    duration: 'Duration:',
                    helpfulQuestion: 'Was this summary helpful?',
                    meetingTitlePlaceholder: 'Meeting title…',
                    noSpeechContent: '(No speech content)',
                    tips: 'Tips',
                    settings: 'Settings',
                    copiedToClipboard: 'Copied to clipboard',
                    copyFailed: 'Copy failed',
                    audioSaved: 'Audio saved',
                    saveFailed: 'Save failed',
                    uploadRecordingFailed: 'Recording upload failed',
                    insertedToDoc: 'Inserted to document',
                    volume: 'Volume',
                    copy: 'Copy',
                    recordingPlayback: 'Recording playback',
                    playRecording: 'Play recording',
                    pausePlayback: 'Pause playback',
                    playbackPosition: 'Recording playback position',
                    audioPlaybackFailed: 'Unable to play the recording. Check that the audio file is accessible.',
                    aiSummary: 'AI Summary',
                    insertToDocument: 'Insert to document',
                    summaryGenerationFailed: 'AI summary generation failed',
                    summaryPlaceholder: 'A summary, decisions, and action items will be generated when the meeting ends…',
                    keyPoints: 'Key points',
                    decisions: 'Decisions',
                    owner: 'Owner',
                    dueDate: 'Due date',
                    selectRecordingFolder: 'Choose meeting recordings folder',
                    fileServiceUnavailable: 'File service is unavailable; the recording is only stored in this browser session',
                    folderNotSelected: 'No recordings folder selected; download a local copy or retry later',
                    stopFailed: 'Failed to stop recording',
                    retrySummary: 'Retry summary',
                    retrySave: 'Retry save',
                    downloadLocalCopy: 'Download local copy',
                    recordingFilePrefix: 'Recording',
                    summaryPrompt: 'Please generate a meeting summary for the following transcript, including:\n1. Meeting topic/title\n2. Key discussion points (listed by item)\n3. Conclusions/decisions\n4. Action items (if any)\n\nTranscript:\n{{transcript}}\n\nPlease reply in Markdown format, clear and readable.',
                },
            },
        },
    },
});

export { SpeechToTextExtension } from './extension';
export { useSpeechRecognition } from './hooks/useSpeechRecognition';
export { speechController, useSpeechController } from './speech-controller';
export { startSpeech } from './extension/menu/RecordingToast';
