import React from 'react';
import { KPlugin, PluginConfig } from '@kn/common';
import { FileAudio } from '@kn/icon';
import { SpeechToTextExtension } from './extension';
import { MeetingMinutesHome } from './pages/MeetingMinutesHome';

interface SpeechToTextPluginConfig extends PluginConfig { }

class SpeechToTextPlugin extends KPlugin<SpeechToTextPluginConfig> { }

export const speechToText = new SpeechToTextPlugin({
    status: 'ACTIVE',
    name: 'Speech to Text',
    editorExtension: [SpeechToTextExtension],
    routes: [
        {
            name: 'meetingMinutes',
            path: '/meeting-minutes',
            element: <MeetingMinutesHome />,
        },
    ],
    menus: [
        {
            id: '/meeting-minutes',
            name: 'meetingMinutes.title',
            key: 'Meeting Minutes',
            icon: <FileAudio className="h-5 w-5" />,
        },
    ],
    locales: {
        zh: {
            translation: {
                speechToText: {
                    title: '语音转文字',
                    start: '语音输入',
                    stop: '停止',
                    pause: '暂停',
                    resume: '继续',
                    listening: '正在聆听…',
                    paused: '已暂停',
                    notSupported: '此浏览器不支持语音识别，请使用 Chrome 或 Edge。',
                },
                meetingMinutes: {
                    title: '会议纪要',
                    homeDescription: '一个会议对应一个独立页面，录音会自动归档到当前空间。',
                    newMeeting: '新建会议',
                    recentMeetings: '最近会议',
                    noMeetings: '暂无会议',
                    noMeetingsDescription: '创建会议页面后即可开始录音和记录。',
                    untitledMeeting: '未命名会议',
                    space: '空间',
                    selectSpaceFirst: '请先选择空间',
                    recordingFolderHint: '录音将自动保存到此空间的固定会议录音目录。',
                    createFailed: '创建会议页面失败',
                    loadFailed: '加载会议纪要失败',
                    meetingTitle: '会议',
                    today: '今天',
                    notes: '笔记',
                    notesPlaceholder: 'AI 会总结笔记和转录内容…',
                    attendees: '参会人',
                    addAttendee: '添加',
                    removeAttendee: '移除',
                    searchAttendeePlaceholder: '搜索成员…',
                    noAttendeesFound: '未找到成员',
                    tags: '标签',
                    language: '识别语言',
                    transcriptionUnavailable: '当前浏览器不支持实时转录，仍会录音（推荐使用 Chrome 或 Edge）。',
                    actionItems: '待办事项',
                    summary: '摘要',
                    transcript: '转录',
                    startTranscribing: '开始转录',
                    pause: '暂停',
                    resume: '继续',
                    stop: '停止',
                    transcribing: '转录中',
                    paused: '已暂停',
                    listening: '聆听中…',
                    liveTranscript: '实时转录',
                    editable: '可编辑',
                    transcriptWillAppear: '转录内容将显示在这里…',
                    processing: '处理中…',
                    generateAISummary: '生成 AI 摘要',
                    generatingSummary: '正在生成摘要…',
                    insertToEditor: '插入到编辑器',
                    chars: '字符',
                    share: '分享',
                    newRecording: '新建录音',
                    saveRecording: '保存录音',
                    howItWorks: '使用方法：',
                    howItWorks1: '点击"开始转录"开始。',
                    howItWorks2: '随时在此添加笔记，AI 会利用它们生成更智能的摘要。',
                    howItWorks3: '完成后点击"停止"，AI 将生成摘要和待办事项。',
                    consentTitle: '选择如何通知他人',
                    consentDesc: '为了让他人知道您正在录音，可以播放音频消息，或您自行获取同意。为所有会议设置默认方式：',
                    consentMyself: '自行获取同意',
                    consentAudio: '自动播放音频',
                    instructions: '说明：',
                    auto: '自动',
                    consentNote: '开始即表示您确认所有被录音的人已同意。',
                    duration: '时长：',
                    helpfulQuestion: '摘要是否有帮助？',
                    meetingTitlePlaceholder: '会议标题…',
                    noSpeechContent: '（无语音内容）',
                    tips: '提示',
                    settings: '设置',
                    copiedToClipboard: '已复制到剪贴板',
                    copyFailed: '复制失败',
                    audioSaved: '录音已保存',
                    saveFailed: '保存失败',
                    uploadRecordingFailed: '录音上传失败',
                    insertedToDoc: '已插入到文档',
                    volume: '音量',
                    copy: '复制',
                    recordingPlayback: '录音回放',
                    aiSummary: 'AI 摘要',
                    insertToDocument: '插入到文档',
                    summaryGenerationFailed: 'AI 摘要生成失败',
                    summaryPlaceholder: '会议结束后会自动生成摘要、决策和待办事项…',
                    keyPoints: '讨论要点',
                    decisions: '会议决策',
                    owner: '负责人',
                    dueDate: '截止日期',
                    selectRecordingFolder: '选择会议录音文件夹',
                    fileServiceUnavailable: '文件服务不可用，录音仅保存在当前浏览器中',
                    folderNotSelected: '未选择录音文件夹，可下载本地副本或稍后重试',
                    stopFailed: '停止录音失败',
                    retrySummary: '重试摘要',
                    retrySave: '重试保存',
                    downloadLocalCopy: '下载本地副本',
                    recordingFilePrefix: '会议录音',
                    summaryPrompt: '请为以下会议录音转录内容生成会议摘要，包括：\n1. 会议主题/标题\n2. 主要讨论内容（按要点列出）\n3. 会议结论/决议\n4. 待办事项（如有）\n\n转录内容：\n{{transcript}}\n\n请用中文回复，格式清晰易读。',
                },
            },
        },
        en: {
            translation: {
                speechToText: {
                    title: 'Speech to text',
                    start: 'Speech to text',
                    stop: 'Stop',
                    pause: 'Pause',
                    resume: 'Resume',
                    listening: 'Listening…',
                    paused: 'Paused',
                    notSupported: 'Speech recognition is not supported in this browser. Please use Chrome or Edge.',
                },
                meetingMinutes: {
                    title: 'Meeting Minutes',
                    homeDescription: 'Create one page per meeting and archive recordings automatically in the current space.',
                    newMeeting: 'New meeting',
                    recentMeetings: 'Recent meetings',
                    noMeetings: 'No meetings yet',
                    noMeetingsDescription: 'Create a meeting page to start recording and taking notes.',
                    untitledMeeting: 'Untitled meeting',
                    space: 'Space',
                    selectSpaceFirst: 'Please select a space first',
                    recordingFolderHint: 'Recordings are saved automatically to this space’s fixed meeting folder.',
                    createFailed: 'Failed to create meeting page',
                    loadFailed: 'Failed to load meeting minutes',
                    meetingTitle: 'Meeting',
                    today: 'Today',
                    notes: 'Notes',
                    notesPlaceholder: 'AI will summarize the notes and transcript…',
                    attendees: 'Attendees',
                    addAttendee: 'Add',
                    removeAttendee: 'Remove',
                    searchAttendeePlaceholder: 'Search members…',
                    noAttendeesFound: 'No members found',
                    tags: 'Tags',
                    language: 'Language',
                    transcriptionUnavailable: 'Live transcription is unavailable in this browser; audio is still recorded (use Chrome or Edge).',
                    actionItems: 'Action items',
                    summary: 'Summary',
                    transcript: 'Transcript',
                    startTranscribing: 'Start transcribing',
                    pause: 'Pause',
                    resume: 'Resume',
                    stop: 'Stop',
                    transcribing: 'Transcribing',
                    paused: 'Paused',
                    listening: 'Listening…',
                    liveTranscript: 'Live transcript',
                    editable: 'Editable',
                    transcriptWillAppear: 'Transcript will appear here…',
                    processing: 'Processing…',
                    generateAISummary: 'Generate AI summary',
                    generatingSummary: 'Generating summary…',
                    insertToEditor: 'Insert to editor',
                    chars: 'chars',
                    share: 'Share',
                    newRecording: 'New recording',
                    saveRecording: 'Save recording',
                    howItWorks: 'How it works:',
                    howItWorks1: 'Click "Start transcribing" to get started.',
                    howItWorks2: 'Add notes here anytime. AI uses them to make the summary smarter.',
                    howItWorks3: 'When you\'re done, click "Stop". AI will generate a summary with action items.',
                    consentTitle: 'Choose how you notify others',
                    consentDesc: 'To let others know you\'re transcribing, an audio message can play automatically, or you can continue to get consent yourself. Set your default for all meetings:',
                    consentMyself: 'Get consent myself',
                    consentAudio: 'Automatically play audio',
                    instructions: 'Instructions:',
                    auto: 'Auto',
                    consentNote: 'By starting, you confirm everyone being transcribed has given consent.',
                    duration: 'Duration:',
                    helpfulQuestion: 'Was this summary helpful?',
                    meetingTitlePlaceholder: 'Meeting title…',
                    noSpeechContent: '(No speech content)',
                    tips: 'Tips',
                    settings: 'Settings',
                    copiedToClipboard: 'Copied to clipboard',
                    copyFailed: 'Copy failed',
                    audioSaved: 'Audio saved',
                    saveFailed: 'Save failed',
                    uploadRecordingFailed: 'Recording upload failed',
                    insertedToDoc: 'Inserted to document',
                    volume: 'Volume',
                    copy: 'Copy',
                    recordingPlayback: 'Recording playback',
                    aiSummary: 'AI Summary',
                    insertToDocument: 'Insert to document',
                    summaryGenerationFailed: 'AI summary generation failed',
                    summaryPlaceholder: 'A summary, decisions, and action items will be generated when the meeting ends…',
                    keyPoints: 'Key points',
                    decisions: 'Decisions',
                    owner: 'Owner',
                    dueDate: 'Due date',
                    selectRecordingFolder: 'Choose meeting recordings folder',
                    fileServiceUnavailable: 'File service is unavailable; the recording is only stored in this browser session',
                    folderNotSelected: 'No recordings folder selected; download a local copy or retry later',
                    stopFailed: 'Failed to stop recording',
                    retrySummary: 'Retry summary',
                    retrySave: 'Retry save',
                    downloadLocalCopy: 'Download local copy',
                    recordingFilePrefix: 'Recording',
                    summaryPrompt: 'Please generate a meeting summary for the following transcript, including:\n1. Meeting topic/title\n2. Key discussion points (listed by item)\n3. Conclusions/decisions\n4. Action items (if any)\n\nTranscript:\n{{transcript}}\n\nPlease reply in Markdown format, clear and readable.',
                },
            },
        },
    },
});

export { SpeechToTextExtension } from './extension';
export { useSpeechRecognition } from './hooks/useSpeechRecognition';
export { speechController, useSpeechController } from './speech-controller';
export { startSpeech } from './extension/menu/RecordingToast';
